# Generated by Django 4.2.6 on 2023-10-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_detail_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='detail_json',
            field=models.JSONField(default=dict),
        ),
    ]
