# Generated by Django 4.2.6 on 2023-10-19 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_detail_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pic',
        ),
    ]
