# Generated by Django 4.2.6 on 2023-10-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_detail_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('current_amount', models.FloatField()),
                ('owner', models.ManyToManyField(to='users.userprofile')),
            ],
        ),
    ]
