# Generated by Django 4.2.6 on 2023-10-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_partition_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partition',
            name='owner',
            field=models.ManyToManyField(to='users.userprofile'),
        ),
    ]
