# Generated by Django 4.2.6 on 2023-10-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userprofile_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='get_bank_account',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partition',
            name='current_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
    ]
