# Generated by Django 4.2.6 on 2023-10-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_partition_id_alter_userprofile_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
