# Generated by Django 4.2.6 on 2023-10-24 03:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_partition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partition',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
