# Generated by Django 4.2.6 on 2023-10-29 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_externalwebapp_user_externalwebapp_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalwebapp',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.externalwebapp'),
        ),
    ]
