# Generated by Django 4.2.6 on 2023-10-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_userprofile_get_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partition',
            name='is_unallocated',
            field=models.BooleanField(default=False),
        ),
    ]
