# Generated by Django 4.2.6 on 2023-10-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_partition_is_unallocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='partition',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
