# Generated by Django 4.2.6 on 2023-10-31 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0025_remove_partition_owner_partition_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partition',
            name='owner',
        ),
        migrations.AddField(
            model_name='partition',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
