# Generated by Django 4.2.6 on 2023-10-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_partition_owner_partition_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partition',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
