# Generated by Django 4.2.6 on 2023-10-31 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_partition_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partition',
        ),
    ]
