# Generated by Django 4.2.6 on 2023-11-03 01:28

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_externalwebapp_client_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access_token',
            field=django_cryptography.fields.encrypt(models.TextField(max_length=30, null=True)),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_refreshed',
            field=django_cryptography.fields.encrypt(models.TimeField(null=True)),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='token_expire_time',
            field=django_cryptography.fields.encrypt(models.IntegerField(default=0)),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='token_type',
            field=django_cryptography.fields.encrypt(models.TextField(max_length=30, null=True)),
        ),
    ]
