# Generated by Django 4.2.6 on 2023-11-03 02:37

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_userprofile_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_refreshed',
            field=django_cryptography.fields.encrypt(models.DateTimeField(null=True)),
        ),
    ]
