# Generated by Django 4.2.6 on 2023-11-03 02:39

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_userprofile_last_refreshed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_refreshed',
            field=django_cryptography.fields.encrypt(models.TimeField(null=True)),
        ),
    ]
