# Generated by Django 4.2.6 on 2023-11-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_userprofile_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='valid_token',
            field=models.BooleanField(default=False),
        ),
    ]
