# Generated by Django 4.2.6 on 2023-11-07 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_userprofile_valid_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bank',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.externalwebapp'),
        ),
    ]
