# Generated by Django 4.2.6 on 2023-11-10 06:47

from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    for profile in UserProfile.objects.all():
        profile.uuid = uuid.uuid4()
        profile.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_userprofile_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
