# Generated by Django 4.2.6 on 2023-11-10 06:59

from django.db import migrations, models
import uuid

def regen_id(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    for prof in UserProfile.objects.all():
        prof.id = uuid.uuid4()
        prof.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_userprofile_id'),
    ]

    operations = [
        migrations.RunPython(regen_id),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
            preserve_default=False
        ),
    ]
