# Generated by Django 4.2.6 on 2023-11-10 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_userprofile_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='uuid',
        ),
    ]
