# Generated by Django 4.2.6 on 2023-11-10 19:34

from django.db import migrations, models
import uuid

def replace_user_id(apps, schema_editor):
    UserProfile = apps.get_model("users", "UserProfile")

    for up in UserProfile.objects.all():
        up.uuid = uuid.uuid4()
        up.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_remove_userprofile_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
        ),
        migrations.RunPython(replace_user_id),
    ]
