# Generated by Django 4.2.6 on 2023-10-31 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_unallocated', models.BooleanField(default=False)),
                ('label', models.CharField(max_length=200)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
