# Generated by Django 4.2.6 on 2023-11-02 05:05

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partition',
            name='label',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200)),
        ),
    ]
