# Generated by Django 4.2.6 on 2023-11-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partitions', '0002_alter_partition_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partition',
            name='label',
            field=models.CharField(max_length=200),
        ),
    ]
