# Generated by Django 4.2.6 on 2023-11-07 06:58

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('partitions', '0005_alter_partition_current_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partition',
            name='init_amount',
            field=django_cryptography.fields.encrypt(models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
        ),
        migrations.CreateModel(
            name='PartitionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('condition_type', models.CharField(choices=[('eq', 'Equals'), ('lt', 'Less Than'), ('gt', 'Greater Than'), ('and', 'And'), ('or', 'Or')], max_length=50)),
                ('condition_value', models.CharField(max_length=255)),
                ('action_type', models.CharField(choices=[('fix', 'Fix Amount')], max_length=50)),
                ('action_value', models.TextField()),
                ('partition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partitions.partition')),
            ],
        ),
    ]
