# Generated by Django 4.2.6 on 2023-11-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partitions', '0006_partition_init_amount_partitionrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='partitionrule',
            name='condition_value_attribute',
            field=models.CharField(choices=[('init_amount', 'Inital Amount'), ('current_amount', 'Current Amount')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
