# Generated by Django 4.2.6 on 2023-11-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partitions', '0007_partitionrule_condition_value_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitionrule',
            name='action_value',
            field=models.CharField(max_length=50),
        ),
    ]
