# Generated by Django 4.2.6 on 2023-11-07 18:17

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partitions', '0008_alter_partitionrule_action_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitionrule',
            name='action_type',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('fix', 'Fix Amount')], max_length=50)),
        ),
        migrations.AlterField(
            model_name='partitionrule',
            name='action_value',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=50)),
        ),
        migrations.AlterField(
            model_name='partitionrule',
            name='condition_type',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('eq', 'Equals'), ('lt', 'Less Than'), ('gt', 'Greater Than'), ('and', 'And'), ('or', 'Or')], max_length=50)),
        ),
        migrations.AlterField(
            model_name='partitionrule',
            name='condition_value',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
        migrations.AlterField(
            model_name='partitionrule',
            name='condition_value_attribute',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('init_amount', 'Inital Amount'), ('current_amount', 'Current Amount')], max_length=50)),
        ),
        migrations.AlterField(
            model_name='partitionrule',
            name='name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=20)),
        ),
    ]
