# Generated by Django 4.2.6 on 2023-11-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partitions', '0009_alter_partitionrule_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitionrule',
            name='action_type',
            field=models.CharField(choices=[('fix', 'Fix Amount')], max_length=50),
        ),
        migrations.AlterField(
            model_name='partitionrule',
            name='action_value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='partitionrule',
            name='condition_type',
            field=models.CharField(choices=[('eq', 'Equals'), ('lt', 'Less Than'), ('gt', 'Greater Than'), ('and', 'And'), ('or', 'Or')], max_length=50),
        ),
        migrations.AlterField(
            model_name='partitionrule',
            name='condition_value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partitionrule',
            name='condition_value_attribute',
            field=models.CharField(choices=[('init_amount', 'Inital Amount'), ('current_amount', 'Current Amount')], max_length=50),
        ),
        migrations.AlterField(
            model_name='partitionrule',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
