# Generated by Django 4.2.6 on 2023-11-07 20:03

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partitions', '0011_remove_partitionrule_condition_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleexpression',
            name='value',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True)),
        ),
    ]
