# Generated by Django 4.2.6 on 2023-11-07 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partitions', '0012_alter_ruleexpression_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleexpression',
            name='parent_expression',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_expr', to='partitions.ruleexpression'),
        ),
    ]
