# Generated by Django 4.2.6 on 2023-11-07 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partitions', '0013_alter_ruleexpression_parent_expression'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleexpression',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partitions.partitionrule'),
        ),
    ]
