# Generated by Django 4.2.6 on 2023-11-07 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partitions', '0014_ruleexpression_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruleexpression',
            name='left_expression',
        ),
        migrations.RemoveField(
            model_name='ruleexpression',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='ruleexpression',
            name='parent_expression',
        ),
        migrations.RemoveField(
            model_name='ruleexpression',
            name='right_expression',
        ),
        migrations.DeleteModel(
            name='PartitionRule',
        ),
        migrations.DeleteModel(
            name='RuleExpression',
        ),
    ]
