# Generated by Django 4.2.6 on 2023-11-08 00:01

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('partitions', '0015_remove_ruleexpression_left_expression_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', django_cryptography.fields.encrypt(models.CharField(max_length=50))),
                ('active', models.BooleanField(default=True)),
                ('entity_id', django_cryptography.fields.encrypt(models.CharField(max_length=50))),
                ('entity_type', django_cryptography.fields.encrypt(models.CharField(max_length=50))),
                ('entity_name', django_cryptography.fields.encrypt(models.CharField(max_length=50))),
                ('attribute', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('attribute_type', django_cryptography.fields.encrypt(models.CharField(max_length=50))),
                ('operation', django_cryptography.fields.encrypt(models.CharField(max_length=10))),
                ('value', django_cryptography.fields.encrypt(models.CharField(max_length=50))),
                ('action', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('partition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partitions.partition')),
            ],
        ),
    ]
