# Generated by Django 4.2.6 on 2023-11-08 01:57

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('partitions', '0016_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleUniopExpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_type', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=20, null=True))),
                ('float_value', django_cryptography.fields.encrypt(models.FloatField(blank=True, null=True))),
                ('decimal_value', django_cryptography.fields.encrypt(models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True))),
                ('string_value', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=50, null=True))),
                ('int_value', django_cryptography.fields.encrypt(models.FloatField(blank=True, null=True))),
            ],
        ),
        migrations.CreateModel(
            name='RuleBiopExpression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operator', django_cryptography.fields.encrypt(models.CharField(blank=True, choices=[('lt', 'Less Than'), ('gt', 'Greater Than')], max_length=20, null=True))),
                ('left_expr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_expression', to='partitions.rulebiopexpression')),
                ('right_expr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_expression', to='partitions.rulebiopexpression')),
                ('value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partitions.ruleuniopexpression')),
            ],
        ),
    ]
