# Generated by Django 4.2.6 on 2023-11-08 01:59

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partitions', '0017_ruleuniopexpression_rulebiopexpression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='action',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True)),
        ),
        migrations.AlterField(
            model_name='rule',
            name='attribute',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True)),
        ),
        migrations.AlterField(
            model_name='rule',
            name='attribute_type',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=50, null=True)),
        ),
        migrations.AlterField(
            model_name='rule',
            name='entity_id',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=50, null=True)),
        ),
        migrations.AlterField(
            model_name='rule',
            name='entity_name',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=50, null=True)),
        ),
        migrations.AlterField(
            model_name='rule',
            name='entity_type',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=50, null=True)),
        ),
        migrations.AlterField(
            model_name='rule',
            name='operation',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=10, null=True)),
        ),
        migrations.AlterField(
            model_name='rule',
            name='value',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=50, null=True)),
        ),
    ]
