# Generated by Django 4.2.6 on 2023-11-08 02:21

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partitions', '0018_alter_rule_action_alter_rule_attribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulebiopexpression',
            name='partition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partitions.partition'),
        ),
        migrations.AlterField(
            model_name='rulebiopexpression',
            name='left_expr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_expression', to='partitions.rulebiopexpression'),
        ),
        migrations.AlterField(
            model_name='rulebiopexpression',
            name='operator',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, choices=[('lt', 'Less Than'), ('gt', 'Greater Than'), ('lte', 'Less Than or Equal'), ('gte', 'Greater Than or Equal')], max_length=20, null=True)),
        ),
        migrations.AlterField(
            model_name='rulebiopexpression',
            name='right_expr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_expression', to='partitions.rulebiopexpression'),
        ),
        migrations.AlterField(
            model_name='rulebiopexpression',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partitions.ruleuniopexpression'),
        ),
        migrations.AlterField(
            model_name='ruleuniopexpression',
            name='value_type',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, choices=[('float', 'Float'), ('decimal', 'Decimal'), ('str', 'String'), ('string', 'String'), ('int', 'Integer')], max_length=20, null=True)),
        ),
    ]
