# Generated by Django 4.2.6 on 2023-11-08 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partitions', '0019_rulebiopexpression_partition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulebiopexpression',
            name='is_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rulebiopexpression',
            name='partition',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='partitions.partition'),
        ),
    ]
