# Generated by Django 4.2.6 on 2023-11-08 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partitions', '0020_rulebiopexpression_is_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulebiopexpression',
            name='partition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partitions.partition'),
        ),
    ]
