# Generated by Django 4.2.6 on 2023-11-08 04:30

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partitions', '0021_alter_rulebiopexpression_partition'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulebiopexpression',
            name='parent_expr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_expression', to='partitions.rulebiopexpression'),
        ),
        migrations.AlterField(
            model_name='ruleuniopexpression',
            name='int_value',
            field=django_cryptography.fields.encrypt(models.IntegerField(blank=True, null=True)),
        ),
    ]
