# Generated by Django 4.2.6 on 2023-11-08 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partitions', '0022_rulebiopexpression_parent_expr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulebiopexpression',
            name='parent_expr',
        ),
        migrations.AddField(
            model_name='rulebiopexpression',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rulebiopexpression',
            name='partition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partitions.partition'),
        ),
    ]
