# Generated by Django 4.2.6 on 2023-11-12 00:46

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partitions', '0028_rulebiopexpression_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulebiopexpression',
            name='action',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=20, null=True)),
        ),
    ]
