# Generated by Django 4.2.6 on 2023-11-21 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partitions', '0029_rulebiopexpression_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulebiopexpression',
            name='transfer_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_from', to='partitions.partition'),
        ),
        migrations.AddField(
            model_name='rulebiopexpression',
            name='transfer_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_to', to='partitions.partition'),
        ),
    ]
