# Generated by Django 4.2.6 on 2023-11-21 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partitions', '0031_rulebiopexpression_transfer_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulebiopexpression',
            name='transfer_from',
        ),
    ]
