# Generated by Django 4.2.6 on 2023-11-21 16:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('partitions', '0033_partition_frozen_rulebiopexpression_preformed_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleuniopexpression',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
