# Generated by Django 4.2.6 on 2023-10-25 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banking', '0004_alter_accountholder_id_alter_bankaccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_holder', to=settings.AUTH_USER_MODEL),
        ),
    ]
